name: Weekly Update

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Run update script
        run: ./update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update data
          title: Weekly update
          body: Update data from the update script
          branch: weekly-update
